//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public Cita()
        {
            this.Detalle_Medicina = new HashSet<Detalle_Medicina>();
            this.Detalle_Servicio = new HashSet<Detalle_Servicio>();
        }
    
        public int Id_Cita { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora_Inico { get; set; }
        public System.TimeSpan Hora_Final { get; set; }
        public string Estado_Cita { get; set; }
        public int Id_Cliente { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Paciente { get; set; }
        public string Descripcion { get; set; }
        public int Costo_Total { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle_Medicina> Detalle_Medicina { get; set; }
        public virtual ICollection<Detalle_Servicio> Detalle_Servicio { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
