//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Cita
    {
        public Cita()
        {
            this.Detalle_Medicina = new HashSet<Detalle_Medicina>();
            this.Detalle_Servicio = new HashSet<Detalle_Servicio>();
        }
    
        public int Id_Cita { get; set; }
        [Required(ErrorMessage = "El campo de Fecha es requerido")]
        [DisplayFormat(DataFormatString = "{0:MM/dd/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Fecha")]
        public System.DateTime Fecha { get; set; }
        [Required(ErrorMessage = "El campo de Hora de Inicio es requerido")]
        [DataType(DataType.Time)]
        [Display(Name = "Hora Inicio")]
        public System.TimeSpan Hora_Inico { get; set; }
        [Required(ErrorMessage = "El campo de Hora de Final es requerido")]
        [DataType(DataType.Time)]
        [Display(Name = "Hora Final")]
        public System.TimeSpan Hora_Final { get; set; }
        public string Estado_Cita { get; set; }
        [Required(ErrorMessage = "El campo de Cliente es requerido")]
        [Display(Name = "Cliente")]
        public int Id_Cliente { get; set; }
        [Required(ErrorMessage = "El campo de Empleado es requerido")]
        [Display(Name = "Empleado")]
        public int Id_Empleado { get; set; }
        [Required(ErrorMessage = "El campo de Paciente es requerido")]
        [Display(Name = "Paciente")]
        public int Id_Paciente { get; set; }
        [Required(ErrorMessage = "El campo de Descripcion es requerido")]
        [StringLength(600, ErrorMessage = "Maximo 600 caracteres")]
        [DataType(DataType.MultilineText)]
        [Display(Name = "Descripcion")]
        public string Descripcion { get; set; }
        [Required(ErrorMessage = "El campo de Costo Total es requerido")]
        [Display(Name = "Costo Total")]
        public int Costo_Total { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle_Medicina> Detalle_Medicina { get; set; }
        public virtual ICollection<Detalle_Servicio> Detalle_Servicio { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
