//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Servicio
    {
        public int Id_Detalle_Servicio { get; set; }
        public int Id_Cita { get; set; }
        public int Id_Servicio { get; set; }
        public int Cantidad { get; set; }
        public int Precio_Total { get; set; }
    
        public virtual Cita Cita { get; set; }
        public virtual Servicio Servicio { get; set; }
    }
}
