//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Factura
    {
        public Factura()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
        }
    
        public int Numero_Factura { get; set; }
        [Required(ErrorMessage = "El campo de Empleado es requerido")]
        [Display(Name = "Empleado")] 
        public int Id_Empleado { get; set; }
        [Required(ErrorMessage = "El campo de Cliente es requerido")]
        [Display(Name = "Cliente")] 
        public Nullable<int> Id_Cliente { get; set; }
        [Required(ErrorMessage = "El campo de Proveedor es requerido")]
        [Display(Name = "Proveedor")] 
        public Nullable<int> Id_Proveedor { get; set; }
        [Required(ErrorMessage = "El campo de Fecha es requerido")]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha")] 
        public System.DateTime Fecha { get; set; }
        [Required(ErrorMessage = "El campo de Precio Total es requerido")]
        [Display(Name = "Precio_Total")] 
        public int Precio_Total { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
