//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicina
    {
        public Medicina()
        {
            this.Cita_Medica = new HashSet<Cita_Medica>();
        }
    
        public int Id_Medicina { get; set; }
        public string Nombre { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual ICollection<Cita_Medica> Cita_Medica { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
