//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paciente
    {
        public Paciente()
        {
            this.Cita = new HashSet<Cita>();
        }
    
        public int Id_Paciente { get; set; }
        public int Id_Cliente { get; set; }
        public string Animal { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public string Raza { get; set; }
        public int Edad { get; set; }
        public int Peso { get; set; }
        public int Id_Estado { get; set; }
        public string PacienteCompleto
        {
            get
            {
                return Animal + " " + Raza + " " + Nombre;
            }
        }
        public virtual ICollection<Cita> Cita { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Estado Estado { get; set; }
    }
}
