//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Persona
    {
        public Persona()
        {
            this.Cliente = new HashSet<Cliente>();
            this.Empleado = new HashSet<Empleado>();
            this.Proveedor = new HashSet<Proveedor>();
        }

        public int Id_Persona { get; set; }
        [Required(ErrorMessage = "El campo de Nombre es requerido")]
        [DataType(DataType.Text)]
        [MinLength(2, ErrorMessage = "Numero debe tener minimo 2 caracteres")]
        [MaxLength(50, ErrorMessage = "Numero debe tener maximo 50 caracteres")]
        [Display(Name = "Nombre")]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "El campo de Apellidos es requerido")]
        [DataType(DataType.Text)]
        [MinLength(2, ErrorMessage = "Numero debe tener minimo 2 caracteres")]
        [MaxLength(50, ErrorMessage = "Numero debe tener maximo 50 caracteres")]
        [Display(Name = "Apellidos")]
        public string Apellidos { get; set; }
        [Required(ErrorMessage = "El campo de Direccion es requerido")]
        [DataType(DataType.MultilineText)]
        [StringLength(300, ErrorMessage = "Maximo 300 caracteres")]
        [Display(Name = "Direccion")]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "El campo de Telefono es requerido")]
        [DataType(DataType.Text)]
        [MinLength(8, ErrorMessage = "Numero debe tener minimo 8 caracteres")]
        [MaxLength(11, ErrorMessage = "Numero debe tener maximo 11 caracteres")]
        [Display(Name = "Telefono")]
        public string Telefono { get; set; }
        public int Id_Estado { get; set; }
        public bool Chk_Cliente { get; set; }
        public bool Chk_Empleado { get; set; }
        public bool Chk_Proveedor { get; set; }

        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}