//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.Detalle_Factura = new HashSet<Detalle_Factura>();
            this.Detalle_Medicina = new HashSet<Detalle_Medicina>();
        }
    
        public int Id_Producto { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public double Precio { get; set; }
        public int Cantidad { get; set; }
        public int Id_Proveedor { get; set; }
        public int Id_Categoria { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual ICollection<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual ICollection<Detalle_Medicina> Detalle_Medicina { get; set; }
        public virtual Estado Estado { get; set; }
        public virtual Proveedor Proveedor { get; set; }
    }
}
