//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIOGRAPHY_OF_PETSFAP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Roles
    {
        public Roles()
        {
            this.Usuarios = new HashSet<Usuarios>();
        }
    
        public int Id_Rol { get; set; }
        public string Descripcion { get; set; }
        public int Id_Estado { get; set; }
    
        public virtual Estado Estado { get; set; }
        public virtual ICollection<Usuarios> Usuarios { get; set; }
    }
}
